### ISSUE TITLE
Clarify how the element works internally in README

### ISSUE THREAD

**Issue by simevidas** [chris-l/bin-packing-grid#1]
> “It will try to fit everything and leave no spaces, but in case there are gaps left, it will create div elements to fill them.”

How does this work? Are the items’ dimensions changed in the process. How? CSS `scale()` transforms?

**Comment by chris-l** [comment]
Well, I did mention that it works by using a bin-packing algorithm.
Bin-packing is about reordering elements, not resizing them.
I agree, however, that is a good idea to specify more about how it works on the README, so I just did it. @7dc0022ab3cab94d380c3d10dca802d560cc4cab

**Comment by simevidas** [comment]
Yup, it’s always a good idea to make the README sufficient for all kinds of visitors, in this case, those who aren’t familiar with the bin-packing algorithm :)

**Comment by chris-l** [comment]
Thanks for the suggestion :)
