### ISSUE TITLE
 Items layout

### ISSUE THREAD

**Issue by agozie** [chris-l/bin-packing-grid#4]
How can I "center-justify" items?

**Comment by chris-l** [comment]
I'm not sure if I understand what you mean.

If you mean that you want to have a box that contain the elements, and have that box centered, then the answer would be to use a div containing the bin-packing-grid element and set the size using css to whatever size you want, and then center that box.

**Comment by agozie** [comment]
Can't I use CSS to center bin-packing-items inside the bin-packing-grid? Enclosing in div and centering div does not work well. I need something like class="layout horizontal wrap center-justified"

**Comment by chris-l** [comment]
bin-packing is an algorithm to optimize the order the elements to avoid gaps (well, this is an oversimplification). The way bin-packing-grid does it is by setting  the `position` as absolute and the `top` and `left` css properties of each bin-packing-item. So no, you can't set the inner position of the bin-packing-item elements. 

Why it does not work well enclosing inside a `div`? It seems to be working fine: http://codepen.io/anon/pen/dodmMr
