### ISSUE TITLE
Suggestion: If a bin-packing-item has a `hidden` attribute, it should not be included in the grid.

### ISSUE THREAD

**Issue by travellhyne** [chris-l/bin-packing-grid#6]
In my case, it's a very expensive operation to remove the children and add them back again when I want to. Rather than removing them, marking them with the attribute `hidden` would be an ideal solution.

**Comment by chris-l** [comment]
Sorry for the time! I completely agree with this idea.

And I just did it: Implemented on dbd18bc1297244ca98782a835b56ad5b9fc515b8.
